server:
  port:8810
spring:
  application:
    name: gateway-
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order-route
          uri: lb://order-service
          predicates:
            - path: /test/**
          filters:
            - PrefixPath: /prefix
# 注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
    fetch-registry: true